version: '3.4'

services:
  database:
    image: postgres
    restart: always
    volumes:
      - ./data_db:/var/lib/postgresql/data
      - ./sql_scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "5up3rS3nha"
        POSTGRES_DB: RESOURCE_DB
    ports:
        - 8080:5432